"""
ModelForgeProvider
==================
A QgsProcessingProvider that exposes:
  1. All custom step algorithms generated by CustomStepAuthorService
  2. The ModelForgeMCPAlgorithm (the NLP → model builder tool)
  3. The AutoLayoutAlgorithm

Register it in the plugin's initProcessing() hook.
"""
from __future__ import annotations

try:
    from qgis.core import QgsProcessingProvider
    _HAS_QGIS = True
except ImportError:
    _HAS_QGIS = False

if _HAS_QGIS:
    class ModelForgeProvider(QgsProcessingProvider):

        def __init__(self):
            super().__init__()
            self._user_algorithms: list = []

        def id(self)          -> str:  return "model_forge"
        def name(self)        -> str:  return "ModelForge"
        def longName(self)    -> str:  return "ModelForge AI Workflow Builder"
        def versionInfo(self) -> str:  return "1.0.0"

        def loadAlgorithms(self):
            from .algorithms.mcp_algorithm    import ModelForgeMCPAlgorithm
            from .algorithms.auto_layout      import AutoLayoutAlgorithm
            from .algorithms.contract_test    import ContractTestAlgorithm
            from .algorithms.custom_step_list import ListCustomStepsAlgorithm

            self.addAlgorithm(ModelForgeMCPAlgorithm())
            self.addAlgorithm(AutoLayoutAlgorithm())
            self.addAlgorithm(ContractTestAlgorithm())
            self.addAlgorithm(ListCustomStepsAlgorithm())

            # Load all user-generated custom step algorithms
            for alg in self._user_algorithms:
                self.addAlgorithm(alg)

        def register_user_algorithm(self, alg):
            """Called by CustomStepAuthorService after code generation + import."""
            try:
                new_name = alg.name()
            except Exception:
                new_name = None

            replaced = False
            if new_name:
                for idx, existing in enumerate(self._user_algorithms):
                    try:
                        if existing.name() == new_name:
                            self._user_algorithms[idx] = alg
                            replaced = True
                            break
                    except Exception:
                        continue
            if not replaced:
                self._user_algorithms.append(alg)

            # Reload provider so QGIS picks up the new algorithm
            self.refreshAlgorithms()

else:
    class ModelForgeProvider:
        pass
