"""Export model JSON to a standalone QGIS Processing Python script."""

from __future__ import annotations

import json
from typing import Any


def export_to_processing_script(
    model_json: dict[str, Any],
    output_path: str,
) -> str:
    """Generate a Processing script (.py) from a model JSON dict."""
    model_name = model_json.get("model_name", "model_forge_workflow")
    safe_name = "".join(c if c.isalnum() or c == "_" else "_" for c in model_name)

    lines = [
        f'"""Auto-generated by Model Forge — {model_name}"""',
        "",
        "from qgis.core import (",
        "    QgsProcessingAlgorithm,",
        "    QgsProcessingParameterNumber,",
        "    QgsProcessingParameterString,",
        "    QgsProcessingParameterVectorLayer,",
        "    QgsProcessingParameterRasterLayer,",
        "    QgsProcessingParameterField,",
        "    QgsProcessingParameterBoolean,",
        "    QgsProcessingParameterCrs,",
        "    QgsProcessingParameterExtent,",
        "    QgsProcessingParameterExpression,",
        "    QgsProcessingParameterFeatureSink,",
        "    QgsProcessingOutputVectorLayer,",
        "    QgsProcessingOutputRasterLayer,",
        "    QgsProcessingOutputNumber,",
        "    QgsProcessingOutputString,",
        "    QgsProcessing,",
        "    QgsFeatureSink,",
        ")",
        "from qgis import processing",
        "from qgis.PyQt.QtCore import QCoreApplication",
        "",
    ]

    # Class definition
    class_name = "".join(w.capitalize() for w in safe_name.split("_")) + "Algorithm"
    lines += [
        f"class {class_name}(QgsProcessingAlgorithm):",
        f'    """{model_name} — generated by Model Forge."""',
        "",
        "    def tr(self, message):",
        f"        return QCoreApplication.translate('{class_name}', message)",
        "",
        "    def name(self):",
        f"        return '{safe_name}'",
        "",
        "    def displayName(self):",
        f"        return self.tr('{model_name}')",
        "",
        "    def group(self):",
        "        return self.tr('ModelForge')",
        "",
        "    def groupId(self):",
        "        return 'model_forge'",
        "",
        "    def createInstance(self):",
        f"        return {class_name}()",
        "",
    ]

    # Input parameters
    inputs = model_json.get("inputs", [])
    input_map = {}
    for inp in inputs:
        name = inp.get("name", "")
        qtype = {
            "source": "QgsProcessingParameterVectorLayer",
            "vector": "QgsProcessingParameterVectorLayer",
            "raster": "QgsProcessingParameterRasterLayer",
            "number": "QgsProcessingParameterNumber",
            "string": "QgsProcessingParameterString",
            "boolean": "QgsProcessingParameterBoolean",
            "field": "QgsProcessingParameterField",
            "crs": "QgsProcessingParameterCrs",
            "extent": "QgsProcessingParameterExtent",
            "sink": "QgsProcessingParameterFeatureSink",
        }.get(inp.get("type", ""), "QgsProcessingParameterString")
        input_map[name] = qtype

    lines.append("    def initAlgorithm(self, config=None):")
    for inp in inputs:
        name = inp.get("name", "")
        qtype = input_map[name]
        label = inp.get("label", name) or name
        param_str = f"        self.addParameter({qtype}('{name}', self.tr('{label}')))"
        lines.append(param_str)

    lines.append("")

    # processAlgorithm
    lines.append("    def processAlgorithm(self, parameters, context, feedback):")

    step_vars = {}
    return_items: list[str] = []
    for i, alg in enumerate(model_json.get("algorithms", [])):
        aid = alg.get("id", f"step_{i}")
        alg_id = alg.get("algorithm_id", "")
        safe_var = f"result_{i}"
        step_vars[aid] = safe_var

        lines.append(f"        # Step {i}: {alg.get('description', aid)}")
        params_strs = []
        for pname, pval in (alg.get("parameters") or {}).items():
            ptype = pval.get("type", "static")
            if ptype == "model_input":
                inp_name = pval.get("input_name", "")
                qtype = input_map.get(inp_name, "QgsProcessingParameterVectorLayer")
                params_strs.append(f"'{pname}': parameters['{inp_name}']")
            elif ptype == "child_output":
                child = pval.get("child_id", "")
                oname = pval.get("output_name", "OUTPUT")
                child_var = step_vars.get(child, "")
                params_strs.append(f"'{pname}': {child_var}['{oname}']")
            elif ptype == "static":
                sv = pval.get("value", "")
                if isinstance(sv, str):
                    sv_esc = sv.replace("'", "\\'")
                    params_strs.append(f"'{pname}': '{sv_esc}'")
                else:
                    params_strs.append(f"'{pname}': {json.dumps(sv)}")
                # Track TEMPORARY_OUTPUT for return wiring
                sv_str = str(sv) if sv is not None else ""
                if sv_str.upper() == "TEMPORARY_OUTPUT":
                    return_items.append(f"'{pname}': {safe_var}['{pname}']")
            else:
                params_strs.append(f"'{pname}': None")

        params_block = ",\n            ".join(params_strs)
        lines.append(f"        {safe_var} = processing.run(")
        lines.append(f"            '{alg_id}',")
        lines.append(f"            {{")
        lines.append(f"            {params_block}")
        lines.append(f"            }},")
        lines.append(f"            context=context,")
        lines.append(f"            feedback=feedback,")
        lines.append(f"        )[0]")
        lines.append("")

    if return_items:
        return_block = ",\n            ".join(return_items)
        lines.append(f"        return {{{return_block}}}")
    else:
        lines.append("        return {}")
    lines.append("")

    code = "\n".join(lines) + "\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(code)

    return output_path
